name: Build Check

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install-build-essential
      run:  sudo apt install build-essential

    - name: checkout
      uses:

    - name: build
      run: make
